### ISSUE TITLE
What's going on?

### ISSUE THREAD

**Issue by eagerashwani** [gildaswise/flutter_phone_auth#2]
I don't know what's going wrong with app
![vid-20190112-wa0001 1](https://user-images.githubusercontent.com/34451016/51070737-49167b80-166c-11e9-80d4-74f404a1d5ee.gif)

**Comment by gildaswise** [comment]
Hey! Could you send the logs when this error happens? Are you sure you did the correct settings and enabled Google sign-in in your Firebase project? Remember, there's the Firebase tutorial that you need to do before going on!

**Comment by eagerashwani** [comment]
Everything is correct, logs are here.
I'm unable to find the issue

Launching lib\main.dart on Redmi Note 4 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
V/BoostFramework(25058): BoostFramework() : mPerf = com.qualcomm.qti.Performance@f8eede6
I/flutter (25058): [AUTH] Setting _isRefreshing (false) to true
I/flutter (25058): ReactiveRefreshIndicator: called onRefresh
I/flutter (25058): [AUTH] Just got user as: null
I/Timeline(25058): Timeline: Activity_launch_request time:1149963 intent:Intent { act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.example.voicesend cmp=com.example.voicesend/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (has extras) }
I/Timeline(25058): Timeline: Activity_launch_request time:1150015 intent:Intent { act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.google.android.gms (has extras) }
I/flutter (25058): [AUTH] Setting _isRefreshing (true) to false
I/flutter (25058): [AUTH] Setting _isRefreshing (false) to true
I/flutter (25058): ReactiveRefreshIndicator: called onRefresh
I/flutter (25058): [AUTH] Just got user as: null
I/Timeline(25058): Timeline: Activity_launch_request time:1167135 intent:Intent { act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.example.voicesend cmp=com.example.voicesend/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (has extras) }
I/Timeline(25058): Timeline: Activity_launch_request time:1167192 intent:Intent { act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.google.android.gms (has extras) }
I/flutter (25058): [AUTH] Setting _isRefreshing (true) to false
