### ISSUE TITLE
Logged in

### ISSUE THREAD

**Issue by zhabyans** [gildaswise/flutter_phone_auth#3]
How to save session after logged in when apps start up?

**Comment by gildaswise** [comment]
You should use this code just as a basis for your main project, not build something from it!

But it's quite easy, all you have to do is check if `FirebaseAuth.instance.getCurrentUser()` returns null. If yes, then there's no logged in user and you should display the signup, if not, then the rest of your app.

**Comment by bhandaribhumin** [comment]
@zhabyans  your code is working? how? please let me know!!!
