### ISSUE TITLE
The getter 'authentication' was called on null.

### ISSUE THREAD

**Issue by ggichure** [gildaswise/flutter_phone_auth#6]
Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The getter 'authentication' was called on null.
Receiver: null
Tried calling: authentication)
At first i was getting error 12500 
```
 if (user == null) {
      user = await _googleSignIn.signIn().catchError(onError);
      Logger.log(TAG, message: "Received $user");
      final GoogleSignInAuthentication googleAuth = await user.authentication;
```

**Comment by gildaswise** [comment]
Hey, have you properly followed the configuration steps on the [google_sign_in](https://pub.dev/packages/google_sign_in#android-integration) page?

Is there any other error above the NoSuchMethodError? I've updated the repo with the latest dependencies, could you try pulling and retrying the tutorial?

**Comment by ggichure** [comment]
thanks,twas my google configuration causing the error.
Also assuming one has several gmail accounts how can we change in between them,or make sure that one phone number is only connected to one account?

**Comment by gildaswise** [comment]
You just have to call both `_googleSignIn.signOut()` and `_firebaseAuth.signOut()` to get the account selector again; and I believe it already handles the "number already attached to another user" exception if you get to that. There's a setting in the Authentication part in your project's Firebase console.
