### ISSUE TITLE
getting FirebaseException when login again 

### ISSUE THREAD

**Issue by paavalan** [gildaswise/flutter_phone_auth#7]
when i try to login again getting error

PlatformException (PlatformException(FirebaseException, User has already been linked to the given provider., null))

in _linkWithPhoneNumber function [linkWithCredential]

**Comment by gildaswise** [comment]
`linkWithCredential` should be called only *once* per account; unfortunately `firebase_auth` doesn't let us do only `verifyPhoneNumber`
